// <auto-generated />
namespace LoginRegister.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changesinusertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changesinusertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202212151122247_changes in user table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
